ARG OS_VERSION=18.04
FROM ubuntu:${OS_VERSION}

# Set home dir 
WORKDIR /home
ENV HOME="/home"

SHELL ["/bin/bash", "-c"]

# [X] Install min essentials
# [X] Install miniconda
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        software-properties-common \
        autoconf \
        automake \
        build-essential \
        cmake \
        git-core \
        libass-dev \
        libfreetype6-dev \
        libgnutls28-dev \
        libmp3lame-dev \
        libsdl2-dev \
        libtool \
        libva-dev \
        libvdpau-dev \
        libvorbis-dev \
        libxcb1-dev \
        libxcb-shm0-dev \
        libxcb-xfixes0-dev \
        meson \
        ninja-build \
        pkg-config \
        texinfo \
        wget \
        yasm \
        zlib1g-dev

SHELL ["/bin/bash", "-c"]
